providers:
  - airtap-sauce
  - airtap-default

browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: '18'
  - name: and_chr
    version: '6.0'

presets:
  local:
    browsers:
      - name: default
  chrome:
    providers:
      - airtap-system
    browsers:
      - name: chrome
        options:
          headless: true
