providers:
  - airtap-sauce
  - airtap-default

browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: android
    version: '6.0'

presets:
  local:
    browsers:
      - name: default
