language: node_js
node_js:
  - 8
branches:
  only:
    - master
addons:
  sauce_connect: true
notifications:
  email: false
script:
  - npm run build
  - npm run test:ci
after_success:
  - npm run coverage
  - npx semantic-release
