language: node_js
node_js:
  - 8
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run build
  - npm run test
  - npm run test:integ
after_success:
  - npm run coverage
  - npx semantic-release

