---
name: CI

# https://github.com/airtap/airtap/blob/65c20af3a5174d1ddc3eaa93df3366f3ee5a37e3/lib/sauce-browser.js#L69
env:
  TRAVIS_JOB_NUMBER: github-actions-${{ github.run_id }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: build
        run: npm run build

      - name: Add loopback host
        run: echo "127.0.0.1 airtap.local" | sudo tee -a /etc/hosts

      - name: unit test
        run: npm run test

      - name: integration test (node)
        run: npm run test:integ-node

      - uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: ${{ env.TRAVIS_JOB_NUMBER }}

      - name: integration test (sauce)
        # if: false # https://github.com/airtap/airtap/issues/297
        run: npm run test:integ-browser
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          TRAVIS_JOB_NUMBER: ${{ env.TRAVIS_JOB_NUMBER }}

      - name: coverage
        run: npm run coverage
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
